import { PrismaClient } from '@prisma/client';
const prisma = new PrismaClient();

async function main() {
  // Create categories
  const categories = {};
  const categoryNames = [
    'Air Rifle Accessories',
    'Air Rifles',
    'Air Pistols',
    'Air Pistol Accessories',
    'CO2 Pistols',
    'Consumables',
    'Electronic Target Systems',
    'Pellets',
    'Scatt Training Systems'
  ];
  for (const name of categoryNames) {
    categories[name] = await prisma.category.upsert({
      where: { name },
      update: {},
      create: { name },
    });
  }

  // Create brands
  const brands = {};
  const brandNames = [
    'TEC-HRO',
    'Walther',
    'Pardini',
    'Morini',
    'Umarex',
    'SCATT',
    'Beretta',
    'Tachus',
    'H&N',
    'RWS',
    'Sauer',
    'Centra',
    'Varga',
    'MEC',
    'QYS',
    'Champion'
  ];
  for (const name of brandNames) {
    brands[name] = await prisma.brand.upsert({
      where: { name },
      update: {},
      create: { name },
    });
  }

  // Category ID mapping
  const categoryIdMap = {
    'Air Rifle Accessories': 1,
    'Air Rifles': 2,
    'Air Pistols': 3,
    'Air Pistol Accessories': 4,
    'CO2 Pistols': 5,
    'Consumables': 6,
    'Electronic Target Systems': 7,
    'Pellets': 8,
    'Scatt Training Systems': 9
  };

  // Create products with features and specifications
  // await prisma.product.create({
  //   data: {
  //     id: 'tec-hro-stativ-3-carbon',
  //     name: 'TEC-HRO STATIV 3.0 CARBON, THE NEW RIFLE TRIPOD',
  //     price: '₹26,000',
  //     numericPrice: 26000,
  //     image: '/lovable-uploads/Tech-HRO Stnad.png',
  //     categoryId: categories['Air Rifle Accessories'].id,
  //     brandId: brands['TEC-HRO'].id,
  //     rating: 4.6,
  //     reviewCount: 15,
  //     soldCount: 35,
  //     inStock: true,
  //     isNew: true,
  //     isHot: true,
  //     shortDescription: 'Ultra-light, stable, and user-friendly carbon tripod for competitive rifle shooters. Features innovative design, quick-release levers, and brilliant colors for maximum performance.',
  //     features: {
  //       create: [
  //         { value: 'New, lighter carbon fiber tubes in five brilliant colors' },
  //         { value: 'Weight-optimized foot construction for stability' },
  //         { value: 'Quick-release lever on rifle and ammunition tray' },
  //         { value: 'Ammunition tray swivels and mounts at multiple heights' },
  //         { value: 'Feet splayed at 100° for increased stability' },
  //         { value: 'Extremely robust yet lightweight (approx. 1.25 kg)' },
  //         { value: 'Max height: 170 cm, folds to 67 cm length' },
  //         { value: 'Easy assembly/disassembly without tools' },
  //         { value: 'Rubber-coated rifle tray for secure placement' },
  //       ],
  //     },
  //     specifications: {
  //       create: [
  //         { key: 'Material', value: 'Carbon fiber tubes, milled aluminum foot unit' },
  //         { key: 'Weight', value: 'Approx. 1.25 kg' },
  //         { key: 'Max Height', value: '170 cm' },
  //         { key: 'Folded Dimensions', value: '67 cm length, 9 cm diameter (with bag)' },
  //         { key: 'Ammunition Tray', value: 'Swiveling, mounts on upper/middle/lower tube' },
  //         { key: 'Foot Design', value: '100° splayed for stability' },
  //         { key: 'Assembly', value: 'Tool-free, quick-release levers' },
  //         { key: 'Compatibility', value: 'Universal for sport rifles' },
  //         { key: 'Country of Manufacture', value: 'Germany' },
  //       ],
  //     },
  //   },
  // });

  const products = [
    {
      id: 'tec-hro-stativ-3-carbon',
      name: 'TEC-HRO STATIV 3.0 CARBON, THE NEW RIFLE TRIPOD',
      price: '₹26,000',
      numericPrice: 26000,
      image: '/lovable-uploads/Tech-HRO Stnad.png',
      category: 'Air Rifle Accessories',
      brandId: brands['TEC-HRO'].id,
      rating: 4.6,
      reviewCount: 15,
      soldCount: 35,
      inStock: true,
      isNew: true,
      isHot: true,
      shortDescription: 'Ultra-light, stable, and user-friendly carbon tripod for competitive rifle shooters. Features innovative design, quick-release levers, and brilliant colors for maximum performance.',
      features: {
        create: [
          { value: 'New, lighter carbon fiber tubes in five brilliant colors' },
          { value: 'Weight-optimized foot construction for stability' },
          { value: 'Quick-release lever on rifle and ammunition tray' },
          { value: 'Ammunition tray swivels and mounts at multiple heights' },
          { value: 'Feet splayed at 100° for increased stability' },
          { value: 'Extremely robust yet lightweight (approx. 1.25 kg)' },
          { value: 'Max height: 170 cm, folds to 67 cm length' },
          { value: 'Easy assembly/disassembly without tools' },
          { value: 'Rubber-coated rifle tray for secure placement' },
        ],
      },
      specifications: {
        create: [
          { key: 'Material', value: 'Carbon fiber tubes, milled aluminum foot unit' },
          { key: 'Weight', value: 'Approx. 1.25 kg' },
          { key: 'Max Height', value: '170 cm' },
          { key: 'Folded Dimensions', value: '67 cm length, 9 cm diameter (with bag)' },
          { key: 'Ammunition Tray', value: 'Swiveling, mounts on upper/middle/lower tube' },
          { key: 'Foot Design', value: '100° splayed for stability' },
          { key: 'Assembly', value: 'Tool-free, quick-release levers' },
          { key: 'Compatibility', value: 'Universal for sport rifles' },
          { key: 'Country of Manufacture', value: 'Germany' },
        ],
      },
    },
    {
      id: 'walther-lg500-itec',
      name: 'Walther LG500 ITEC Triple Edition',
      price: '₹249,999',
      numericPrice: 249999,
      image: '/lovable-uploads/44b2615c-e47e-41de-b6c4-97af839d9903.png',
      category: 'Air Rifles',
      brandId: brands['Walther'].id,
      rating: 4.9,
      reviewCount: 42,
      inStock: true,
      isNew: true,
      shortDescription: 'The Walther LG500 itec marks a new era in competitive shooting, redefining perfection with its advanced features and cutting edge innovations. Whether a seasoned competitor or an aspiring champion, the Walther LG500 itec promises an unmatched shooting experience that will lead you straight to the podium.',
      features: {
        create: [
          { value: 'Electronic trigger integrated into grip' },
          { value: 'Perfected grip ergonomics' },
          { value: 'Grip and trigger infinitely adjustable in length, cast and angle' },
          { value: 'Right and left handed grip options in S, M and L sizes' },
          { value: 'Vibration minimized system for optimal response' },
          { value: 'Adaptive inline impulse equalizer' },
          { value: 'Vibration minimized loading mechanics' },
          { value: 'Pneumatically driven absorber' },
          { value: '90g balancing elements in forend and buttstock are infinitely adjustable' },
          { value: 'Independent adjustment of length of pull and cheekpiece position' },
          { value: 'Infinite lateral fine adjustment of cheekpiece' },
          { value: 'Innovative aerospace-grade aluminum buttplate with infinite adjustment' },
        ],
      },
      specifications: {
        create: [
          { key: 'Caliber', value: '.177 (4.5mm)' },
          { key: 'Trigger', value: 'Electronic BTe trigger' },
          { key: 'Grip', value: 'MEMORY 3D-grip BIOMETRIC, right- or left-hand, S/M/L sizes' },
          { key: 'Propulsion', value: 'Compressed air, 300/200 bar' },
          { key: 'Shot Capacity', value: 'Approx. 500 shots per fill' },
          { key: 'Max Energy', value: '7.5 Joules' },
          { key: 'Barrel', value: 'Match-grade, precision rifled' },
          { key: 'Weight Distribution', value: 'Adjustable balancing system' },
          { key: 'Stock', value: 'Infinitely adjustable, ergonomic design' },
          { key: 'Sights', value: 'Visionic Match Diopter, micro-precise' },
          { key: 'Country of Manufacture', value: 'Germany' },
          { key: 'Intended Use', value: 'Professional competition, Olympic shooting' },
        ],
      },
    },
    {
      id: 'pardini-k12-j-short',
      name: 'Pardini K12 J Short',
      price: '₹189,999',
      numericPrice: 189999,
      image: '/lovable-uploads/5818a836-9981-47bc-bfb7-4efb566262b6.png',
      category: 'Air Pistols',
      brandId: brands['Pardini'].id,
      rating: 4.8,
      reviewCount: 36,
      inStock: true,
      isNew: true,
      isHot: false, // isHot was not present in raw data, defaulted to false
      soldCount: 0, // soldCount was not present, defaulted to 0
      shortDescription: 'The Pardini K12 J Short is a competition air pistol designed for precision target shooting, featuring a short grip design for enhanced control and comfort.',
      features: {
        create: [
          { value: 'Short grip design for improved control' },
          { value: 'Adjustable trigger for personalized feel' },
          { value: 'High-precision barrel' },
          { value: 'Integrated compensator for reduced recoil' },
          { value: 'Ergonomic and lightweight construction' },
          { value: 'Suitable for competitive shooting' },
        ],
      },
      specifications: {
        create: [
          { key: 'Caliber', value: '.177 (4.5mm)' },
          { key: 'Action', value: 'Single shot, pre-charged pneumatic (PCP)' },
          { key: 'Cylinder', value: 'Removable, compressed air up to 250 bar' },
          { key: 'Barrel Length', value: '205 mm' },
          { key: 'Overall Length', value: '380 mm' },
          { key: 'Weight', value: '~950 g' },
          { key: 'Grip', value: 'Anatomical, available in RH: XS/S/M/L, LH: S/M/L' },
          { key: 'Trigger', value: 'Fully adjustable, mechanical' },
          { key: 'Sights', value: 'Adjustable rear sight, fixed front sight' },
          { key: 'Compensator', value: 'Integrated, recoil elimination system' },
          { key: 'Country of Manufacture', value: 'Italy' },
          { key: 'Intended Use', value: 'Precision target shooting, ISSF competition' },
        ],
      },
    },
    {
      id: 'morini-electronic-grip-right',
      name: 'Morini Electronic grip for Right hand shooters',
      price: '₹35,000',
      numericPrice: 35000,
      image: '/lovable-uploads/Morini_LeftGrip.png',
      category: 'Air Pistol Accessories',
      brandId: brands['Morini'].id,
      rating: 4.2,
      reviewCount: 4,
      soldCount: 13,
      inStock: true,
      isNew: true,
      isHot: true,
      shortDescription: 'Precision-crafted electronic grip for right-handed shooters, compatible with Morini CM162EI air pistols. Adjustable ergonomic design for optimal control and comfort in competitive shooting.',
      features: {
        create: [
          { value: 'Handmade from high-quality walnut wood' },
          { value: 'Designed for right-handed shooters' },
          { value: 'Electronic trigger compatibility (CM162EI)' },
          { value: 'Adjustable palm shelf for custom fit' },
          { value: 'Enhanced ergonomics for improved stability' },
          { value: 'CNC-machined for precision' },
          { value: 'Available in multiple sizes (XS, S, M, L, XL, XXL)' },
          { value: 'Smooth finish for comfortable grip' },
          { value: 'Ideal for ISSF and Olympic-level air pistol competition' },
        ],
      },
      specifications: {
        create: [
          { key: 'Material', value: 'Premium walnut wood' },
          { key: 'Compatibility', value: 'Morini CM162EI electronic air pistol' },
          { key: 'Hand Orientation', value: 'Right' },
          { key: 'Sizes Available', value: 'XS, S, M, L, XL, XXL' },
          { key: 'Palm Shelf', value: 'Adjustable, CNC-machined' },
          { key: 'Finish', value: 'Smooth, ergonomic' },
          { key: 'Trigger', value: 'Electronic (for CM162EI)' },
          { key: 'Country of Manufacture', value: 'Switzerland' },
          { key: 'Intended Use', value: 'Precision air pistol sport shooting' },
        ],
      },
    },
    {
      id: 'umarex-co2-cartridges',
      name: 'Umarex 12g CO2 Cartridges (Capsules)',
      price: '₹1,499',
      numericPrice: 1499,
      image: '/lovable-uploads/343e01c8-d47b-4613-9aad-6f7197159da6.png',
      category: 'Consumables',
      brandId: brands['Umarex'].id,
      rating: 4.7,
      reviewCount: 128,
      inStock: true,
      isNew: true,
      isHot: false, // isHot was not present in raw data, defaulted to false
      soldCount: 0, // soldCount was not present, defaulted to 0
      shortDescription: 'High-quality 12g CO2 cartridges for air pistols and rifles, designed to provide consistent power and reliable performance for a variety of airguns.',
      features: {
        create: [
          { value: '12g CO2 cartridges for airguns' },
          { value: 'Consistent and reliable power output' },
          { value: 'Compatible with most air pistols and rifles' },
          { value: 'Leak-proof design for maximum efficiency' },
          { value: 'Ideal for target shooting and plinking' },
        ],
      },
      specifications: {
        create: [
          { key: 'Cartridge Size', value: '12 grams' },
          { key: 'Material', value: 'High-grade metal' },
          { key: 'Type', value: 'Non-threaded CO2 capsule' },
          { key: 'Compatibility', value: 'Fits most CO2-powered air pistols and rifles' },
          { key: 'Seal Quality', value: 'Tight tolerances for precise fit, leak-proof' },
          { key: 'Gas Purity', value: 'Tested for clean, reliable CO2' },
          { key: 'Country of Manufacture', value: 'Germany' },
          { key: 'Intended Use', value: 'Power source for airguns, paintball, airsoft' },
        ],
      },
    },
    {
      id: 'scatt-mx-w2',
      name: 'SCATT MX-W2 WI-FI',
      price: '₹90,000',
      numericPrice: 90000,
      image: '/lovable-uploads/e284a5bc-98e2-45a3-b9b1-11aea9dadfb1.png',
      category: 'Scatt Training Systems',
      brandId: brands['SCATT'].id,
      rating: 4.9,
      reviewCount: 17,
      inStock: true,
      isNew: true,
      isHot: false, // isHot was not present in raw data, defaulted to false
      soldCount: 0, // soldCount was not present, defaulted to 0
      shortDescription: 'The SCATT MX-W2 is an advanced wireless training system for professional shooters, offering real-time feedback and analysis to improve accuracy and performance.',
      features: {
        create: [
          { value: 'Wireless (Wi-Fi) connectivity for easy setup' },
          { value: 'Real-time shot analysis and feedback' },
          { value: 'Compatible with various firearms and airguns' },
          { value: 'Portable and lightweight design' },
          { value: 'Comprehensive training software included' },
        ],
      },
      specifications: {
        create: [
          { key: 'Use', value: 'Indoor and outdoor dry-fire/live-fire training' },
          { key: 'Distance to Target', value: '2.5 to 1000 meters' },
          { key: 'Optical Sensor Type', value: 'Wireless (Wi-Fi 2.4 GHz) or USB wired' },
          { key: 'Optical Sensor Size', value: '34 x 35 x 60 mm' },
          { key: 'Optical Sensor Weight', value: '56 g' },
          { key: 'Supported Platforms', value: 'Windows, macOS, Linux, iOS, Android' },
          { key: 'Included Accessories', value: 'Iris diaphragm, mounting prism, mounting plate, hex key, charging cable, flash drive, quick setup guide, carrying case' },
          { key: 'Warranty', value: '2 years (limited)' },
          { key: 'Ammunition Compatibility', value: 'Up to .338 cal' },
          { key: 'Country of Manufacture', value: 'Russia' },
          { key: 'Intended Use', value: 'Professional shooting training, analysis, and feedback' },
        ],
      },
    },
    {
      id: 'walther-lg500',
      name: 'Walther LG500',
      price: '₹249,999',
      numericPrice: 249999,
      image: '/lovable-uploads/94816e34-750a-420e-b8fc-bde67a9fe267.png',
      category: 'Air Rifles',
      brandId: brands['Walther'].id,
      rating: 5.0,
      reviewCount: 0, // reviewCount was not present, defaulted to 0
      soldCount: 89,
      inStock: true,
      isNew: false, // isNew was not present, defaulted to false
      isHot: true,
      shortDescription: 'The Walther LG500 is a premium competition air rifle designed for professional shooters, offering advanced technology and precision engineering for top-level performance.',
      features: {
        create: [
          { value: 'High-precision match barrel' },
          { value: 'Adjustable stock and cheekpiece' },
          { value: 'Electronic or mechanical trigger options' },
          { value: 'Ergonomic design for optimal handling' },
          { value: 'Advanced recoil absorption system' },
          { value: 'Customizable balance and weight distribution' },
          { value: 'Suitable for world-class competition' },
        ],
      },
      specifications: {
        create: [
          { key: 'Caliber', value: '.177 (4.5mm)' },
          { key: 'Trigger', value: 'Electronic or mechanical, adjustable' },
          { key: 'Propulsion', value: 'Pre-charged pneumatic (PCP), 300/200 bar' },
          { key: 'Barrel', value: 'Match-grade, precision rifled' },
          { key: 'Stock', value: 'Adjustable, ergonomic design' },
          { key: 'Weight', value: '~4.2 kg (varies by configuration)' },
          { key: 'Length', value: 'Approx. 1070 mm' },
          { key: 'Sights', value: 'Match diopter, adjustable' },
          { key: 'Energy', value: 'Up to 7.5 Joules' },
          { key: 'Grip', value: 'Anatomical, right/left hand options' },
          { key: 'Country of Manufacture', value: 'Germany' },
          { key: 'Intended Use', value: 'Professional competition, Olympic shooting' },
        ],
      },
    },
    {
      id: 'beretta-px4-storm',
      name: 'Pietro Beretta Px4 Storm',
      price: '₹89,999',
      numericPrice: 89999,
      image: '/lovable-uploads/81cbd973-5303-4c06-bfdf-36f0555888f8.png',
      category: 'CO2 Pistols',
      brandId: brands['Beretta'].id,
      rating: 4.8,
      reviewCount: 0, // reviewCount was not present, defaulted to 0
      soldCount: 132,
      inStock: true,
      isNew: false, // isNew was not present, defaulted to false
      isHot: true,
      shortDescription: 'The Beretta Px4 Storm is a reliable CO2-powered air pistol featuring an innovative rotating barrel system for realistic blowback action and enhanced shooting experience.',
      features: {
        create: [
          { value: 'CO2-powered semi-automatic action' },
          { value: 'Innovative rotating barrel system' },
          { value: 'Realistic blowback for authentic feel' },
          { value: 'Drop-free magazine for quick reloading' },
          { value: 'Ergonomic grip for comfortable handling' },
          { value: 'Integrated accessory rail' },
        ],
      },
      specifications: {
        create: [
          { key: 'Caliber', value: '.177 (4.5mm) BB or pellet' },
          { key: 'Action', value: 'CO2-powered, semi-automatic, blowback' },
          { key: 'Velocity', value: 'Up to 380 fps' },
          { key: 'Barrel', value: 'Rifled, 4.1 in (104 mm)' },
          { key: 'Overall Length', value: '7.6 in (193 mm)' },
          { key: 'Weight', value: '1.6 lbs (726 g)' },
          { key: 'Magazine Capacity', value: '16 rounds (2 x 8-shot rotary magazines)' },
          { key: 'Trigger', value: 'Double-action & single-action' },
          { key: 'Sights', value: 'Blade front, fixed rear' },
          { key: 'Safety', value: 'Manual' },
          { key: 'Powerplant', value: '12g CO2 capsule' },
          { key: 'Shots per Fill', value: '~40' },
          { key: 'Country of Manufacture', value: 'Germany (Umarex, licensed by Beretta)' },
          { key: 'Intended Use', value: 'Plinking, training, fun shooting' },
        ],
      },
    },
    {
      id: 'tachus-10-ets',
      name: 'Tachus 10 ETS',
      price: '₹150,000',
      numericPrice: 150000,
      image: '/lovable-uploads/aa897794-9610-4c04-9c17-d3928750fc0e.png',
      category: 'Electronic Target Systems',
      brandId: brands['Tachus'].id,
      rating: 4.7,
      reviewCount: 0, // reviewCount was not present, defaulted to 0
      soldCount: 76,
      inStock: true,
      isNew: false, // isNew was not present, defaulted to false
      isHot: true,
      shortDescription: 'The Tachus 10 ETS is a precision electronic target system designed for training and competition, providing instant feedback and high accuracy for shooters.',
      features: {
        create: [
          { value: 'Electronic scoring for instant feedback' },
          { value: 'High-precision target sensors' },
          { value: 'Wireless connectivity for easy setup' },
          { value: 'Compatible with various calibers and airguns' },
          { value: 'Durable and weather-resistant construction' },
          { value: 'User-friendly interface for training and competition' },
        ],
      },
      specifications: {
        create: [
          { key: 'Application', value: '10m air rifle and pistol ISSF events' },
          { key: 'Technology', value: 'Acoustic sensor-based scoring' },
          { key: 'Target Movement', value: 'Automatic paper roll advancement after each shot' },
          { key: 'Scoring Software', value: 'Windows 7/8/10 compatible, real-time analytics' },
          { key: 'Illumination', value: 'Adjustable internal LED system' },
          { key: 'Maintenance', value: 'Removable pellet trap' },
          { key: 'Installation', value: 'Simple, suitable for home and range' },
          { key: 'Accuracy', value: 'ISSF-compliant, high precision' },
          { key: 'Country of Manufacture', value: 'India' },
          { key: 'Intended Use', value: 'Personal training, club competitions, professional events' },
        ],
      },
    },
    {
      id: 'pardini-k12-absorber',
      name: 'Pardini K12 Absorber Pistol',
      price: '₹189,999',
      numericPrice: 189999,
      image: '/lovable-uploads/9d861ad0-08bd-4f35-9567-bf07dbe5551b.png',
      category: 'Air Pistols',
      brandId: brands['Pardini'].id,
      rating: 4.9,
      reviewCount: 0, // reviewCount was not present, defaulted to 0
      soldCount: 105,
      inStock: true,
      isNew: false, // isNew was not present, defaulted to false
      isHot: true,
      shortDescription: 'The Pardini K12 Absorber is a top-tier air pistol equipped with an advanced recoil absorption system for maximum stability and precision in competitive shooting.',
      features: {
        create: [
          { value: 'Advanced recoil absorption system' },
          { value: 'Adjustable trigger for custom feel' },
          { value: 'Precision match-grade barrel' },
          { value: 'Ergonomic anatomical grip' },
          { value: 'Adjustable rear sight' },
          { value: 'Lightweight and balanced design' },
        ],
      },
      specifications: {
        create: [
          { key: 'Caliber', value: '.177 (4.5mm)' },
          { key: 'Action', value: 'Single shot, pre-charged pneumatic (PCP)' },
          { key: 'Cylinder', value: 'Removable, 250 bar max pressure' },
          { key: 'Barrel', value: 'Match-grade, alloy sleeve with up to 8 counterweights' },
          { key: 'Weight', value: '~970 g (varies by configuration)' },
          { key: 'Grip', value: 'Anatomical, multiple sizes/colors' },
          { key: 'Trigger', value: 'Fully adjustable, mechanical' },
          { key: 'Absorber', value: 'Integrated recoil reduction system' },
          { key: 'Sights', value: 'Adjustable rear, fixed front' },
          { key: 'Customization', value: '24 color variations (sleeve/cylinder)' },
          { key: 'Country of Manufacture', value: 'Italy' },
          { key: 'Intended Use', value: 'Olympic and ISSF competition, precision target shooting' },
        ],
      },
    },
    {
      id: 'hn-excite-econ-ii',
      name: 'H&N Excite Econ II',
      price: '₹400',
      numericPrice: 400,
      image: '/lovable-uploads/EXCITE PELLET.jpg',
      category: 'Pellets',
      brandId: brands['H&N'].id,
      rating: 4.5,
      reviewCount: 85,
      inStock: true,
      isNew: false, // isNew was not present, defaulted to false
      isHot: false, // isHot was not present in raw data, defaulted to false
      soldCount: 0, // soldCount was not present, defaulted to 0
      shortDescription: 'The H&N Excite Econ II is a lightweight, accurate pellet for plinking, hobby shooting, and CO2 pistols. It features an updated head design for improved performance and is ideal for universal use at an extremely favorable price.',
      features: {
        create: [
          { value: 'Lightweight design for higher velocity' },
          { value: 'Consistent size and weight for accuracy' },
          { value: 'Updated head design for improved performance' },
          { value: 'Ideal for plinking, hobby shooting, and CO2 pistols' },
          { value: 'Suitable for universal use' },
          { value: 'Affordable price' },
        ],
      },
      specifications: {
        create: [
          { key: 'Caliber', value: '.177 (4.5mm)' },
          { key: 'Pellet Weight', value: '7.4 grains (0.48 g)' },
          { key: 'Pellet Shape', value: 'Flat-head (wadcutter), diabolo' },
          { key: 'Material', value: 'Lead' },
          { key: 'Quantity per Tin', value: '500' },
          { key: 'Surface', value: 'Smooth' },
          { key: 'Head Design', value: 'Updated for improved performance' },
          { key: 'Country of Manufacture', value: 'Germany' },
          { key: 'Intended Use', value: 'Plinking, hobby shooting, CO2 pistols, universal use' },
        ],
      },
    },
    {
      id: 'rws-diabolo-basic',
      name: 'RWS Diabolo Basic',
      price: '₹475',
      numericPrice: 475,
      image: '/lovable-uploads/GREEN DIABOLO.jpg',
      category: 'Pellets',
      brandId: brands['RWS'].id,
      rating: 4.6,
      reviewCount: 92,
      inStock: true,
      isNew: false, // isNew was not present, defaulted to false
      isHot: false, // isHot was not present in raw data, defaulted to false
      soldCount: 0, // soldCount was not present, defaulted to 0
      shortDescription: 'The RWS Diabolo Basic wadcutter (flat-nose) pellet provides everything you need in a basic target shooting pellet. Made in Germany for consistent size and weight, it is ideal for lower-powered airguns and offers reliable accuracy for practice and plinking.',
      features: {
        create: [
          { value: 'Wadcutter (flat-nose) design for clean target holes' },
          { value: 'Consistent size and weight for accuracy' },
          { value: 'Ideal for lower-powered airguns' },
          { value: 'Reliable accuracy for practice and plinking' },
          { value: 'Made in Germany for quality assurance' },
        ],
      },
      specifications: {
        create: [
          { key: 'Caliber', value: '.177 (4.5mm)' },
          { key: 'Pellet Weight', value: '0.45 g / 6.94 grains' },
          { key: 'Pellet Shape', value: 'Wadcutter, flat nose, Diabolo' },
          { key: 'Material', value: 'Lead' },
          { key: 'Surface', value: 'Smooth' },
          { key: 'Quantity per Tin', value: '300' },
          { key: 'Country of Manufacture', value: 'Germany' },
          { key: 'Intended Use', value: 'Target shooting, practice, plinking, lower-powered airguns' },
        ],
      },
    },
    {
      id: 'rws-r10-pistol',
      name: 'RWS R10 Pistol Pellets',
      price: '₹950',
      numericPrice: 950,
      image: '/lovable-uploads/R10 PISTOL.jpg',
      category: 'Pellets',
      brandId: brands['RWS'].id,
      rating: 4.7,
      reviewCount: 61,
      inStock: true,
      isNew: false, // isNew was not present, defaulted to false
      isHot: false, // isHot was not present in raw data, defaulted to false
      soldCount: 0, // soldCount was not present, defaulted to 0
      shortDescription: 'RWS R10 Match Pistol pellets are manufactured using a special production and control process for maximum dimensional accuracy and consistency. Selected material properties, tight tolerances, and professional shooting tests ensure top quality for competition use.',
      features: {
        create: [
          { value: 'Match-grade quality for competition use' },
          { value: 'Manufactured with special production and control process' },
          { value: 'Maximum dimensional accuracy and consistency' },
          { value: 'Selected material properties and tight tolerances' },
          { value: 'Professional shooting tests for quality assurance' },
        ],
      },
      specifications: {
        create: [
          { key: 'Caliber', value: '.177 (4.5mm)' },
          { key: 'Head Size', value: '4.50 mm' },
          { key: 'Pellet Weight', value: '0.45 g / 7.0 grains' },
          { key: 'Pellet Shape', value: 'Wadcutter, flat nose' },
          { key: 'Bullet Length', value: '5.4 mm' },
          { key: 'Material', value: 'Lead' },
          { key: 'Quantity per Tin', value: '500' },
          { key: 'Manufacturing', value: 'Premium line, optoelectronically inspected' },
          { key: 'Country of Manufacture', value: 'Germany' },
          { key: 'Intended Use', value: 'Professional and competitive air pistol sport shooting' },
        ],
      },
    },
    {
      id: 'sauer-top-ten-shooting-gloves',
      name: 'Sauer Top Ten Shooting Gloves',
      price: '₹6,500',
      numericPrice: 6500,
      originalPrice: 7500, // Kept this as it might be a new field in your schema
      image: '/lovable-uploads/sauer-top-ten-gloves.png',
      category: 'Air Rifle Accessories',
      brandId: brands['Sauer'].id,
      rating: 4.7,
      reviewCount: 15,
      soldCount: 89,
      inStock: true,
      isNew: false,
      isHot: true,
      shortDescription: 'Premium leather shooting gloves with rubber inserts for optimal weight distribution and grip.',
      features: {
        create: [
          { value: 'High-quality rubber inserts on back and palm' },
          { value: 'Open fingertips for improved ventilation and loading' },
          { value: 'Wide elasticated band for snug wrist fit' },
          { value: 'ISSF compliant design' },
          { value: 'Available for both left and right hand' },
        ],
      },
      specifications: {
        create: [
          { key: 'Material', value: '87% leather, 9% polyester, 2% polyamide, 1% polyurethane, 1% elastane' },
          { key: 'Lining', value: '100% polyester' },
          { key: 'Inserts', value: '100% high-quality rubber' },
          { key: 'Sizes Available', value: 'XS, S, M, L, XL' },
          { key: 'Hand Options', value: 'Left Hand, Right Hand' },
          { key: 'Weight', value: 'Approximately 150g' },
          { key: 'Country of Manufacture', value: 'Germany' },
        ],
      },
    },
    {
      id: 'centra-spy-short-sight',
      name: 'Centra Spy Short Sight',
      price: '₹59,300',
      numericPrice: 59300,
      image: '/lovable-uploads/centra-spy-short-sight.png',
      category: 'Air Rifle Accessories',
      brandId: brands['Centra'].id,
      rating: 4.8,
      reviewCount: 23,
      soldCount: 34,
      inStock: true,
      isNew: false,
      isHot: false,
      shortDescription: 'Precision rear sight designed for 10m air rifle and 50m 3P events with excellent wind flag visibility.',
      features: {
        create: [
          { value: 'Extremely slim and compact design' },
          { value: 'Built-in anti-glare tube' },
          { value: '24 clicks per rotation for precise adjustment' },
          { value: 'Windage knobs on both sides (ambidextrous)' },
          { value: 'Enhanced wind flag visibility' },
          { value: 'Improved spatial perception for better balance' },
        ],
      },
      specifications: {
        create: [
          { key: 'Clicks per Rotation', value: '24' },
          { key: 'Adjustment per Click at 10m', value: '0.2mm' },
          { key: 'Adjustment per Click at 50m', value: '1mm' },
          { key: 'Adjustment per Click at 100m', value: '2mm' },
          { key: 'Adjustment per Click at 300m', value: '6mm' },
          { key: 'Mount Type', value: 'Single clamp (sufficient for air rifles)' },
          { key: 'Tube', value: 'Anti-glare design' },
          { key: 'Suitable for', value: '10m air rifle, 50m 3P, wind shooting' },
          { key: 'Country of Manufacture', value: 'Germany' },
        ],
      },
    },
    {
      id: 'centra-sight-3-0-basic',
      name: 'Centra Sight 3.0 Basic',
      price: '₹22,500',
      numericPrice: 22500,
      image: '/lovable-uploads/centra-sight-3-basic.png',
      category: 'Air Rifle Accessories',
      brandId: brands['Centra'].id,
      rating: 4.6,
      reviewCount: 31,
      soldCount: 67,
      inStock: true,
      isNew: false,
      isHot: false,
      shortDescription: 'Standard iris aperture with precision adjustment for improved contrast and depth of focus.',
      features: {
        create: [
          { value: 'Precision iris with 15 adjustment discs' },
          { value: 'Interchangeable sight covers' },
          { value: 'Insertable color filters' },
          { value: 'Polished colored glass filters available' },
          { value: 'Integrated clamp element for eye covering' },
          { value: 'Improved handling with new filter control rings' },
        ],
      },
      specifications: {
        create: [
          { key: 'Adjustable Range', value: '0.5 - 3.0mm' },
          { key: 'Iris Discs', value: '15 precision discs' },
          { key: 'Thread', value: 'M 9.5 x 1' },
          { key: 'Colors Available', value: 'Black, Red, Silver, Blue' },
          { key: 'Filter Options', value: 'Multiple colored glass filters' },
          { key: 'Eye Cover', value: 'Integrated clamp element' },
          { key: 'Version', value: 'Standard' },
          { key: 'Country of Manufacture', value: 'Germany' },
        ],
      },
    },
    {
      id: 'varga-shooting-frame',
      name: 'Varga Shooting Frame',
      price: '₹28,900',
      numericPrice: 28900,
      originalPrice: 32000, // Kept this as it might be a new field in your schema
      image: '/lovable-uploads/varga-shooting-frame.png',
      category: 'Air Rifle Accessories',
      brandId: brands['Varga'].id,
      rating: 4.5,
      reviewCount: 18,
      soldCount: 45,
      inStock: true,
      isNew: true,
      isHot: false,
      shortDescription: 'Professional rifle shooting frame with adjustable components for optimal sight picture.',
      features: {
        create: [
          { value: 'Square-headed frame prevents movement while shooting' },
          { value: 'New aluminum fittings for extra strength' },
          { value: 'Matt silver finish' },
          { value: 'Complete with ISSF flip-up blinder' },
          { value: 'Adjustable lens holder with multiple positioning angles' },
          { value: 'Adjustable nose bridge' },
          { value: 'Suitable for all rifle shooting disciplines' },
        ],
      },
      specifications: {
        create: [
          { key: 'Frame Type', value: 'Rifle shooting frame' },
          { key: 'Material', value: 'Aluminum fittings with square head design' },
          { key: 'Finish', value: 'Matt silver' },
          { key: 'Lens Holder', value: '23mm, fully adjustable' },
          { key: 'Eye Shield', value: 'ISSF compliant 30mm white flip-up blinder' },
          { key: 'Nose Bridge', value: 'Curved, offset, fully adjustable' },
          { key: 'Clamping', value: 'New clamp design with left/right positioning' },
          { key: 'Weight', value: 'Lightweight design' },
          { key: 'Suitable For', value: 'All rifle disciplines' },
        ],
      },
    },
    {
      id: 'mec-centra-contact-iv-buttplate',
      name: 'MEC Centra Contact IV Buttplate',
      price: '₹22,000',
      numericPrice: 22000,
      image: '/lovable-uploads/mec-contact-iv-buttplate.png',
      category: 'Air Rifle Accessories',
      brandId: brands['MEC'].id,
      rating: 4.9,
      reviewCount: 12,
      soldCount: 28,
      inStock: true,
      isNew: false,
      isHot: true,
      shortDescription: 'Advanced buttplate with fully adjustable wings and precise height adjustment for perfect fit.',
      features: {
        create: [
          { value: 'Hand adjustable screw for vernier height adjustment' },
          { value: 'Additional joints for variable adjustments' },
          { value: 'Exchangeable wing forms' },
          { value: 'Fully adjustable and revolvable wings' },
          { value: 'Natural rubber knops for perfect grip' },
          { value: 'Compatible with all common match rifles' },
          { value: 'Central plate rotatable around main vertical column' },
        ],
      },
      specifications: {
        create: [
          { key: 'Weight', value: 'Approximately 220g' },
          { key: 'Wing Adjustment', value: 'Fully adjustable vertically, horizontally, and rotatable' },
          { key: 'Height Adjustment', value: 'Vernier precision with hand-adjustable screw' },
          { key: 'Grip Material', value: 'Natural uncured rubber knops' },
          { key: 'Wing Forms', value: 'Interchangeable' },
          { key: 'Compatibility', value: 'All common match rifles' },
          { key: 'Suitable Disciplines', value: 'Offhand air rifle, 3-position, rest shooting' },
          { key: 'Generation', value: 'Fourth generation Contact series' },
          { key: 'Country of Manufacture', value: 'Germany' },
        ],
      },
    },
    {
      id: 'walther-lg500-itec-e',
      name: 'Walther LG500 ITEC E',
      price: '₹5,50,000',
      numericPrice: 550000,
      image: '/lovable-uploads/walther-lg500-itec-e.png',
      category: 'Air Rifles',
      brandId: brands['Walther'].id,
      rating: 4.9,
      reviewCount: 8,
      soldCount: 12,
      inStock: true,
      isNew: true,
      isHot: true,
      shortDescription: 'Revolutionary air rifle with electronic trigger technology and systematic balance optimization for Olympic-level performance.',
      features: {
        create: [
          { value: 'Biometric Trigger Electronic (BTe) with infinite adjustability' },
          { value: 'Walther Stability & Response System (SRS) for reduced vibration' },
          { value: 'Balancing System with 90g elements in forend and buttstock' },
          { value: 'Accuracy Control System (ACS) with perfected barrel interface' },
          { value: 'ITEC System Bedding eliminates stress from barreled system' },
          { value: 'Visionic Match Diopter with micro adjustable ball-bearing guide' },
          { value: 'Aerospace-grade aluminum buttplate with infinite adjustments' },
        ],
      },
      specifications: {
        create: [
          { key: 'Caliber', value: '4.5mm / .177' },
          { key: 'Max Energy', value: '7.5 Joules' },
          { key: 'Trigger System', value: 'Electronic BTe with biometric grip integration' },
          { key: 'Grip', value: 'MEMORY 3D-grip BIOMETRIC (S/M/L sizes)' },
          { key: 'Balancing Elements', value: '90g in forend and buttstock' },
          { key: 'Barrel', value: 'Lothar Walther precision barrel' },
          { key: 'Stock', value: 'Split buttstock with independent adjustments' },
          { key: 'Sight', value: 'Visionic Match Diopter with secondary sight' },
          { key: 'Weight', value: 'Approximately 4.2kg' },
          { key: 'Country of Manufacture', value: 'Germany' },
        ],
      },
    },
    {
      id: 'morini-cm-162mi',
      name: 'MORINI CM 162MI',
      price: '₹1,94,700',
      numericPrice: 194700,
      image: '/lovable-uploads/morini-cm-162mi.png',
      category: 'CO2 Pistols',
      brandId: brands['Morini'].id,
      rating: 4.8,
      reviewCount: 19,
      soldCount: 27,
      inStock: true,
      isNew: false,
      isHot: true,
      shortDescription: 'Competition air pistol with mechanical trigger, Lothar Walther precision barrel and 200 guaranteed shots per charge.',
      features: {
        create: [
          { value: 'Pre-charged natural air system (200 bar)' },
          { value: '200 guaranteed shots when charged to 200 bar' },
          { value: 'Two detachable cylinders with pressure gauges' },
          { value: 'Lothar Walther precision barrel based on Morini concept' },
          { value: 'Factory anatomical adjustable walnut grips' },
          { value: 'Muzzle compensator eliminates barrel flip' },
          { value: 'Mechanical trigger with ball bearing and dry-fire mechanism' },
          { value: 'Unique low pressure lock for shot consistency' },
        ],
      },
      specifications: {
        create: [
          { key: 'Caliber', value: '4.5mm / .177' },
          { key: 'Trigger', value: 'Mechanical with ball bearing, ISSF compliant' },
          { key: 'Barrel', value: 'Lothar Walther precision barrel' },
          { key: 'Charging Pressure', value: '200 bar (3000 psi)' },
          { key: 'Shot Count', value: '200 shots guaranteed per charge' },
          { key: 'Grips', value: 'Anatomical adjustable walnut (right/left available)' },
          { key: 'Foresight', value: '5.0mm standard (4.0, 4.5, 5.5, 6.0mm extra)' },
          { key: 'Weight', value: 'Approximately 970g' },
          { key: 'Length', value: '410mm' },
          { key: 'Country of Manufacture', value: 'Switzerland' },
        ],
      },
    },
    {
      id: 'qys-training-grade-pellets',
      name: 'QYS Training Grade 4.49MM, .177 Cal, 500 Pellets',
      price: '₹2,800',
      numericPrice: 2800,
      originalPrice: 3200, // Kept this as it might be a new field in your schema
      image: '/lovable-uploads/qys-training-pellets.png',
      category: 'Pellets',
      brandId: brands['QYS'].id,
      rating: 4.6,
      reviewCount: 45,
      soldCount: 156,
      inStock: true,
      isNew: false,
      isHot: false,
      shortDescription: 'High-quality training grade pellets used by international shooters with 2.2mm max group size at 10 meters.',
      features: {
        create: [
          { value: 'Used by many international shooters including Olympic medalists' },
          { value: 'Maximum average group size of 2.2mm at 10 meters' },
          { value: 'Can stand upright at 45-degree angle without external influence' },
          { value: 'Precision manufactured for consistent performance' },
          { value: 'Wadcutter nose design for clean holes in targets' },
          { value: 'Individually quality checked pellets' },
          { value: 'Equivalent to RWS R10 performance level' },
        ],
      },
      specifications: {
        create: [
          { key: 'Caliber', value: '.177 / 4.5mm' },
          { key: 'Head Size', value: '4.49mm' },
          { key: 'Weight', value: '0.53g (8.18 grains)' },
          { key: 'Shape', value: 'Wadcutter Nose' },
          { key: 'Count', value: '500 pellets per tin' },
          { key: 'Group Size', value: '≤2.2mm at 10m (12 shot average)' },
          { key: 'Grade', value: 'Training Grade' },
          { key: 'Packaging', value: 'Screw-lid tin' },
          { key: 'Country of Manufacture', value: 'China' },
        ],
      },
    },
    {
      id: 'champion-super-olympic-pistol-frame',
      name: 'Champion Super Olympic Pistol Frame',
      price: '₹42,800',
      numericPrice: 42800,
      image: '/lovable-uploads/champion-super-olympic-frame.png',
      category: 'Air Pistol Accessories',
      brandId: brands['Champion'].id,
      rating: 4.9,
      reviewCount: 14,
      soldCount: 22,
      inStock: true,
      isNew: false,
      isHot: true,
      shortDescription: 'Ultimate precision shooting glasses frame with 96 components and micro-adjustability without tools.',
      features: {
        create: [
          { value: '96 different precision-engineered components' },
          { value: 'Complete hand micro-adjustability without tools' },
          { value: 'Adjustments possible while in firing position' },
          { value: 'Nosepiece offset for extreme alignment adjustments' },
          { value: 'Individual height and inclination adjustments' },
          { value: 'Micro-adjustable lens turning and distance to eye' },
          { value: 'Swiss precision engineering at its finest' },
          { value: 'Compatible with prescription lenses' },
        ],
      },
      specifications: {
        create: [
          { key: 'Components', value: '96 precision-engineered parts' },
          { key: 'Adjustments', value: '5 micro-adjustment axes' },
          { key: 'Height Adjustment', value: 'Individual vertical shift' },
          { key: 'Lens Inclination', value: 'Front/back tilt adjustment' },
          { key: 'Lens Rotation', value: 'Left/right turning on vertical axis' },
          { key: 'Distance Settings', value: '4 positions to eye' },
          { key: 'Nosepiece', value: 'Offset left/right for extreme positions' },
          { key: 'Material', value: 'Swiss precision titanium and advanced alloys' },
          { key: 'Hand Options', value: 'Right-handed and left-handed versions' },
          { key: 'Country of Manufacture', value: 'Switzerland' },
        ],
      },
    },
  ]

  // When creating products, set categoryId: categoryIdMap[product.category]
  for (const product of products) {
    const { category, ...productData } = product;
    await prisma.product.create({
      data: {
        ...productData,
        categoryId: categoryIdMap[category],
        // brandId is already set correctly
      },
    });
  }

  // Create a demo user
  await prisma.user.upsert({
    where: { email: 'admin@example.com' },
    update: {},
    create: {
      email: 'admin@example.com',
      password: 'password123',
      name: 'Admin User',
    },
  });

  console.log('Database seeded!');
}

main().catch(e => {
  console.error(e);
  process.exit(1);
}).finally(() => prisma.$disconnect()); 